# Generated by Django 4.2 on 2023-04-10 13:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, verbose_name='URL категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=ckeditor.fields.RichTextField(verbose_name='Описание*'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ценник(сум)'),
        ),
    ]
